lp-149 Tiltfile required to run local image
companieshouse/limited-partnerships-api pull request #6
Opened 2024-10-29 11:18 UTC by mattch1

JIRA: https://companieshouse.atlassian.net/browse/LP-149

Added tiltfile based on what we have for the oe api.

2024-10-29 15:46 UTC, markpit approved these changes

2024-10-29 17:25 UTC, dlloyd1-ch reviewed
Can we not run the the docker image without tilt? Tilt is being deprecated.

2024-10-29 17:30 UTC, JoelClemence requested changes
I'd be keen to work out why this is needed and why docker compose won't work for this application? Can we discuss this please?

2024-10-30 10:10 UTC, mattch1 commented
Not required so will close this PR.

2024-10-30 10:10 UTC, closed without merging